# C++ 异常处理

### 异常处理介绍

(1) 异常是程序在执行期间产生的问题（编译期出现的错误在写代码时开发环境就有提示）。 C++的异常是指程序运行时发生的特殊情况。

(2) 异常提供了一种转移程序控制权的方式。C++的异常处理涉及到三个关键字：try，catch， throw。

1. throw：当问题出现时，程序会抛出一个异常。这是通过throw关键字来完成的。&#x20;
2. catch：在你想要处理问题的地方，通过异常处理程序捕获异常。catch关键字用于 捕获异常。&#x20;
3. try：try 块中的代码标识将被激活的特定异常。它后面通常跟着一个或多个 catch 块。 如果有一个块抛出一个异常，捕获异常的方法会使用try和catch关键字。try块中放可 能抛出异常的代码，try块中的代码被称为保护代码。常见的异常处理格式如下

```cpp
try {
    // 保护代码
    
}
catch(Exception e1) {
    // catch块
}
catch(Exception e2) {
    // catch块
}
...
catch(Exception eN) {
    // catch块
}
```

(3) 抛出异常：throw 语句可以在代码块的任何地方抛出异常，throw抛出的表达式的结果决 定了抛出的异常的类型。
